version: '3.4'

services:
  nhea.corecommunicationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - 'MAILQUEUE_CONNECTION=<connectionstring>'
      - 'MAILQUEUE_SMTPSETTINGS=<smtpsettingsjson>'
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro